### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by Mrliu88888888** [Longxr/QtAddressBar#2]
![a](https://user-images.githubusercontent.com/51469101/106610308-95112180-65a1-11eb-8cba-d29023bb831d.png)
想请教这一栏中的数据是如何添加上的，谢谢

**Comment by 55CG970NC** [comment]
MenuWidget里面装了个QListview

**Comment by Longxr** [comment]
目录数据的话，可以参考QDirModel、QFileSystemModel
